services:
  pvpedia-server:
    container_name: pvpedia-server
    image: ${SERVER_IMAGE:-ghcr.io/tommypreel/pvpedia-server:latest}
    restart: always
    environment:
      - PORT=3850
    ports:
      - "3850:80"
    networks:
      - web

  pvpedia-client:
    container_name: pvpedia-client
    image: ${CLIENT_IMAGE:-ghcr.io/tommypreel/pvpedia-client:latest}
    restart: always
    ports:
      - "3800:80"
    depends_on:
      - pvpedia-server
    networks:
      - web

networks:
  web:
    external: true
    name: web
